//keyword to create case class is case class className

case class CarDetails(Name:String,Model:String){
  val carName=Name
  val carModel=Model
  def printCarDetails()={
    println(s"Car name is ${carName} and Car model is ${carModel}")
  }

}

object caseClassA {
  def main(args: Array[String]): Unit = {
     val bmw=CarDetails(Name = "BMW",Model = "GT330")
    //No need to write new as apply method is autogenerated in case class
    //For case class,the constructor parameters(eg. Name and Model) are by default val. Therefore value can't be reassigned
    //bmw.Name="B.M.W."
    //So to allow reassigning, you can specify 'var' for constructor parameters in case class. for eg.
    //case class CarDetails(var Name:String,var Model:String)
     bmw.printCarDetails()
    //case class autogenerates unapply and copy method
    val mercedes=bmw.copy(Name = "Mercedes")
    mercedes.printCarDetails()
    //also autogenerates equals and hashcode method
    println(bmw==mercedes)
    println(bmw!=mercedes)
    //to string method is also auto implemented
    println(bmw)
  }

}
